config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources:articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article<ApplicationRecord
    validates :title,presence: true,length: {minimum: 3,maximum: 50}
    validates :description,presence: true,length: {minimum: 3,maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController<ApplicationController
        def new
            @article=Article.new
           
        end

        def index 
            @articles=Article.all
        end


        def create 
            @article=Article.new(article_params)
            if @article.save

                flash[:notice] = "Article was successfuly created"
                redirect_to article_path(@article.id)

            else

                render 'new'

            end
        end


        def show 

            @article=Article.find(params[:id])
        end

        def edit
                
            @article=Article.find(params[:id])

        end

        def update
            @article=Article.find(params[:id])
           if @article.update(article_params)
            flash[:notice]="the articel was updated succesfully"
            redirect_to article_path(@article)
           else
            render 'edit'
           end

        end


        def destroy 
            @article=Article.find(params[:id])
            @article.destroy
            flash[:notice]="article was deleted successfuly"
            redirect_to articles_path
        end
        private

        def article_params
            params.require(:article).permit(:title,:description)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any?%>
    <h2>The following errors prevented the article from getting created</h2>
    <ul>
    <%@article.errors.full_messages.each do |msg|%>
        <li><%=msg%></li>
    <%end%>
    </ul>
<%end%>


<%= form_for @article do |f| %>
    <p>
        <%= f.label :title%>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :description%>
        <%= f.text_area :description%>
    </p>

    <p>
        <%= f.submit %>
    </p>

    <% end %>

app/views/articles/edit.html.erb
<h1> Edit an exsisting article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1> Listing all articles</h1>

<p>
    <%= link_to "Create articles", new_article_path %>
</p>

<table>
    <tr>
        <th>Title</th>
        <th>Description</th>
     </tr>

    <%@articles.each do |article|%>
    <tr>
   
    <td><%=article.title%></td>
    <td><%=article.description%></td>
    <td><%= link_to "Edit", edit_article_path(article) %></td>
    <td><%= link_to "Show", article_path(article)  %></td>
    <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>

   
   
     </tr>

      <%end%>
    
</table>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form'%>

app/views/articles/show.html.erb
<h1>Welcome to Show Page</h1>

<p>
    Title:<%=@article.title%>
</p>

<p>
    Description:<%=@article.description%>
</p>

<p>
<%= link_to "Edit article", edit_article_path(@article) %>
<%= link_to "Back to article listing", articles_path %>
</p>

app/views/layouts/_messages.html.erb
<% flash.each do|name,msg|%>
<ul>
    <li><%=msg%></li>
</ul>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%=render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>